# fly.toml app configuration file for quo-belvo-backend
app = 'quo-belvo-backend'
primary_region = 'fra'

[build]
  platform = "linux/amd64"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  BELVO_API_URL = "https://sandbox.belvo.com/api"
  DEBUG = "False"
  ENV = "production"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

# Esta sección asegura que HTTPS se fuerce correctamente en Fly.io
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.force_https]
    enabled = true
