# fly.toml app configuration file generated for quo-belvo-backend on 2025-04-12T21:21:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quo-belvo-backend'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  BELVO_API_URL = "https://sandbox.belvo.com/api"
  DEBUG = "False"
  ENV = "production"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024